### ISSUE TITLE
Failing mongodb integration test (using mongodb-memory-server)

### ISSUE THREAD

**Issue by meenakshi-dhanani** [thoughtworks/epirust#6]
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
The build is **failing** with the following message when it runs tests for the server.

To replicate the issue, run the following commands in the epirust directory:
````
cd web/server
npm install
npm run test
````

Note: We have reverted the test file commit, you can check it out here - [4dbadd](https://github.com/thoughtworks/epirust/commit/4dbadd7af03411f981db9ee079bb2b1f43791cd8). Please check the [simulation.integration.test.js](https://github.com/thoughtworks/epirust/blob/4dbadd7af03411f981db9ee079bb2b1f43791cd8/web/server/test/controllers/simulation.integration.test.js) file for changes.

**Comment by bawaji94** [comment]
The tests are working fine from this [commit](https://github.com/thoughtworks/epirust/commit/20f8139bf338c92131f0ce2f6289405f869799c4) onwards.
